/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author PC22
 */
public class ViewRentas extends javax.swing.JPanel {

    /**
     * Creates new form ViewRentas
     */
    public ViewRentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_id_renta1 = new javax.swing.JLabel();
        jl_id_cliente = new javax.swing.JLabel();
        jl_formato = new javax.swing.JLabel();
        jl_id_pelicula1 = new javax.swing.JLabel();
        jl_costo = new javax.swing.JLabel();
        jl_total = new javax.swing.JLabel();
        jl_dias1 = new javax.swing.JLabel();
        jtf_id_cliente = new javax.swing.JTextField();
        jtf_costo = new javax.swing.JTextField();
        jtf_id_renta = new javax.swing.JTextField();
        jtf_formato = new javax.swing.JTextField();
        jtf_id_pelicula = new javax.swing.JTextField();
        jtf_dias = new javax.swing.JTextField();
        jtf_total = new javax.swing.JTextField();
        jbtn_primero = new javax.swing.JButton();
        jbtn_anterior = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jbtn_ultimo = new javax.swing.JButton();
        jbtn_agregar = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();
        jbtn_actualizar = new javax.swing.JButton();

        jl_id_renta1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jl_id_renta1.setForeground(new java.awt.Color(204, 153, 255));
        jl_id_renta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_id_renta1.setText("Id de Renta");

        jl_id_cliente.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jl_id_cliente.setForeground(new java.awt.Color(204, 153, 255));
        jl_id_cliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_id_cliente.setText("Id de cliente");

        jl_formato.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jl_formato.setForeground(new java.awt.Color(204, 153, 255));
        jl_formato.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_formato.setText("Formato");

        jl_id_pelicula1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jl_id_pelicula1.setForeground(new java.awt.Color(204, 153, 255));
        jl_id_pelicula1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_id_pelicula1.setText("Id de Pelicula");

        jl_costo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jl_costo.setForeground(new java.awt.Color(204, 153, 255));
        jl_costo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_costo.setText("Costo por dia");

        jl_total.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jl_total.setForeground(new java.awt.Color(204, 153, 255));
        jl_total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_total.setText("Total en renta");

        jl_dias1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jl_dias1.setForeground(new java.awt.Color(204, 153, 255));
        jl_dias1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_dias1.setText("Dias");

        jtf_id_cliente.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jtf_id_cliente.setForeground(new java.awt.Color(204, 153, 255));

        jtf_costo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jtf_costo.setForeground(new java.awt.Color(204, 153, 255));

        jtf_id_renta.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jtf_id_renta.setForeground(new java.awt.Color(204, 153, 255));

        jtf_formato.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jtf_formato.setForeground(new java.awt.Color(204, 153, 255));

        jtf_id_pelicula.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jtf_id_pelicula.setForeground(new java.awt.Color(204, 153, 255));

        jtf_dias.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jtf_dias.setForeground(new java.awt.Color(204, 153, 255));

        jtf_total.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jtf_total.setForeground(new java.awt.Color(204, 153, 255));

        jbtn_primero.setBackground(new java.awt.Color(204, 153, 255));
        jbtn_primero.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtn_primero.setText("l<");

        jbtn_anterior.setBackground(new java.awt.Color(204, 153, 255));
        jbtn_anterior.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtn_anterior.setText("<");

        jbtn_siguiente.setBackground(new java.awt.Color(204, 153, 255));
        jbtn_siguiente.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtn_siguiente.setText(">");

        jbtn_ultimo.setBackground(new java.awt.Color(204, 153, 255));
        jbtn_ultimo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtn_ultimo.setText(">l");

        jbtn_agregar.setBackground(new java.awt.Color(204, 153, 255));
        jbtn_agregar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtn_agregar.setText("Agregar");

        jbtn_eliminar.setBackground(new java.awt.Color(204, 153, 255));
        jbtn_eliminar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtn_eliminar.setText("Eliminar");

        jbtn_actualizar.setBackground(new java.awt.Color(204, 153, 255));
        jbtn_actualizar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtn_actualizar.setText("Actualizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn_primero, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jbtn_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jbtn_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jbtn_ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_dias1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_dias, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_total, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_costo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_costo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_id_pelicula1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_id_pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_formato, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_formato, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_id_renta1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_id_renta, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jbtn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_id_cliente)
                    .addComponent(jtf_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_id_renta1)
                    .addComponent(jtf_id_renta, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_id_pelicula1)
                    .addComponent(jtf_id_pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_formato)
                    .addComponent(jtf_formato, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_costo)
                    .addComponent(jtf_costo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_dias1)
                    .addComponent(jtf_dias, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_total)
                    .addComponent(jtf_total, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_primero)
                    .addComponent(jbtn_anterior)
                    .addComponent(jbtn_siguiente)
                    .addComponent(jbtn_ultimo))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_agregar)
                    .addComponent(jbtn_eliminar)
                    .addComponent(jbtn_actualizar))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbtn_actualizar;
    public javax.swing.JButton jbtn_agregar;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_eliminar;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    public javax.swing.JLabel jl_costo;
    public javax.swing.JLabel jl_dias1;
    public javax.swing.JLabel jl_formato;
    public javax.swing.JLabel jl_id_cliente;
    public javax.swing.JLabel jl_id_pelicula1;
    public javax.swing.JLabel jl_id_renta1;
    public javax.swing.JLabel jl_total;
    public javax.swing.JTextField jtf_costo;
    public javax.swing.JTextField jtf_dias;
    public javax.swing.JTextField jtf_formato;
    public javax.swing.JTextField jtf_id_cliente;
    public javax.swing.JTextField jtf_id_pelicula;
    public javax.swing.JTextField jtf_id_renta;
    public javax.swing.JTextField jtf_total;
    // End of variables declaration//GEN-END:variables
}
