/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package views;

/**
 *
 * @author PC22
 */
public class ViewPeliculas extends javax.swing.JPanel {

    /** Creates new form ViewPeliculas */
    public ViewPeliculas() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtf_nombreP = new javax.swing.JTextField();
        jbtn_actualizar = new javax.swing.JButton();
        jtf_formato = new javax.swing.JTextField();
        jtf_id_pelicula = new javax.swing.JTextField();
        Id_Pelicula = new javax.swing.JLabel();
        jtf_descripcion = new javax.swing.JTextField();
        jl_formato = new javax.swing.JLabel();
        jbtn_primero = new javax.swing.JButton();
        jl_duracion = new javax.swing.JLabel();
        jbtn_anterior = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jl_descripcion = new javax.swing.JLabel();
        jbtn_ultimo = new javax.swing.JButton();
        jl_nombreP = new javax.swing.JLabel();
        jbtn_agregar = new javax.swing.JButton();
        jtf_duracion = new javax.swing.JTextField();
        jbtn_eliminar = new javax.swing.JButton();

        jtf_nombreP.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jtf_nombreP.setForeground(new java.awt.Color(204, 153, 255));

        jbtn_actualizar.setBackground(new java.awt.Color(204, 153, 255));
        jbtn_actualizar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtn_actualizar.setText("Actualizar");

        jtf_formato.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jtf_formato.setForeground(new java.awt.Color(204, 153, 255));

        jtf_id_pelicula.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jtf_id_pelicula.setForeground(new java.awt.Color(204, 153, 255));

        Id_Pelicula.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Id_Pelicula.setForeground(new java.awt.Color(204, 153, 255));
        Id_Pelicula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Id_Pelicula.setText("Id de Pelicula");

        jtf_descripcion.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jtf_descripcion.setForeground(new java.awt.Color(204, 153, 255));

        jl_formato.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jl_formato.setForeground(new java.awt.Color(204, 153, 255));
        jl_formato.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_formato.setText("Formato");

        jbtn_primero.setBackground(new java.awt.Color(204, 153, 255));
        jbtn_primero.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtn_primero.setText("l<");

        jl_duracion.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jl_duracion.setForeground(new java.awt.Color(204, 153, 255));
        jl_duracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_duracion.setText("Duracion");

        jbtn_anterior.setBackground(new java.awt.Color(204, 153, 255));
        jbtn_anterior.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtn_anterior.setText("<");

        jbtn_siguiente.setBackground(new java.awt.Color(204, 153, 255));
        jbtn_siguiente.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtn_siguiente.setText(">");

        jl_descripcion.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jl_descripcion.setForeground(new java.awt.Color(204, 153, 255));
        jl_descripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_descripcion.setText("Descripcion");

        jbtn_ultimo.setBackground(new java.awt.Color(204, 153, 255));
        jbtn_ultimo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtn_ultimo.setText(">l");

        jl_nombreP.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jl_nombreP.setForeground(new java.awt.Color(204, 153, 255));
        jl_nombreP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_nombreP.setText("Nombre");

        jbtn_agregar.setBackground(new java.awt.Color(204, 153, 255));
        jbtn_agregar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtn_agregar.setText("Agregar");

        jtf_duracion.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jtf_duracion.setForeground(new java.awt.Color(204, 153, 255));

        jbtn_eliminar.setBackground(new java.awt.Color(204, 153, 255));
        jbtn_eliminar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jbtn_eliminar.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Id_Pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_id_pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_nombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_nombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_formato, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_formato, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtn_primero, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jbtn_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jbtn_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jbtn_ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jl_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jl_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Id_Pelicula)
                    .addComponent(jtf_id_pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nombreP)
                    .addComponent(jtf_nombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_formato)
                    .addComponent(jtf_formato, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_duracion)
                    .addComponent(jtf_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_descripcion)
                    .addComponent(jtf_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_primero)
                    .addComponent(jbtn_anterior)
                    .addComponent(jbtn_siguiente)
                    .addComponent(jbtn_ultimo))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_agregar)
                    .addComponent(jbtn_eliminar)
                    .addComponent(jbtn_actualizar))
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Id_Pelicula;
    public javax.swing.JButton jbtn_actualizar;
    public javax.swing.JButton jbtn_agregar;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_eliminar;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    public javax.swing.JLabel jl_descripcion;
    public javax.swing.JLabel jl_duracion;
    public javax.swing.JLabel jl_formato;
    public javax.swing.JLabel jl_nombreP;
    public javax.swing.JTextField jtf_descripcion;
    public javax.swing.JTextField jtf_duracion;
    public javax.swing.JTextField jtf_formato;
    public javax.swing.JTextField jtf_id_pelicula;
    public javax.swing.JTextField jtf_nombreP;
    // End of variables declaration//GEN-END:variables

}
